---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# wildboottestjlr

## Installation

Julia needs to be installed. 

``` r
# clone wildboottestjlr from github
# then 
# install(path_to_wildboottestjlr)

```
## Example 

To initiate the package, run

```{r}
library(wildboottestjlr)
wildboottestjlr_setup("C:/Users/alexa/AppData/Local/Programs/Julia-1.6.3/bin")
```

This will initiate Julia and load WildBootTest.jl. 

Note: currently, only a method for `lm` is implemented. The lm method only works for simple cases (the boottest & fwildclusterboot defaults). Further, the data objects are not sorted, so all inference will be incorrect. 

```{r}
data(voters)
lm_fit <- lm(proposition_vote ~ treatment  + log_income, data = voters)
boottest(lm_fit, clustid = "group_id1", B = 999, param = "treatment")

```



